#ifndef SHARED_TAXONOMY_GAME_CONSTANT_H
#define SHARED_TAXONOMY_GAME_CONSTANT_H

#define MIN_PARTICIPANTS 5
#define MAX_PARTICIPANTS 7
#define TOTAL_KICKS 7
#define MIN_ZONE 0
#define MAX_ZONE 5
#define MAX_NAME_LENGTH 30

#define MENU_EXIT 0
#define MENU_REGISTRATION 1
#define MENU_SCORING 2
#define MENU_RANKING 3
#define MENU_SEARCH 4
#define MENU_RECAP 5

#endif /* SHARED_TAXONOMY_GAME_CONSTANT_H */
