/* SANITIZER — Taxonomy */
#ifndef TAXONOMY_SANITIZE_ERROR_H
#define TAXONOMY_SANITIZE_ERROR_H

typedef enum {
    SANITIZE_OK,
    SANITIZE_ERROR_NULL_INPUT,
    SANITIZE_ERROR_TOO_LONG,
    SANITIZE_ERROR_INVALID_CHARS
} SanitizeError;

#endif /* TAXONOMY_SANITIZE_ERROR_H */
