/* EXPORT — Error Enum */
#ifndef SHARED_TAXONOMY_EXPORT_ERROR_H
#define SHARED_TAXONOMY_EXPORT_ERROR_H

typedef enum {
    EXP_OK = 0,
    EXP_ERROR_FILE_NOT_FOUND,
    EXP_ERROR_PERMISSION,
    EXP_ERROR_FORMAT,
    EXP_ERROR_EMPTY_DATA
} ExportError;

#endif /* SHARED_TAXONOMY_EXPORT_ERROR_H */
