/* STORAGE — Error Enum */
#ifndef SHARED_TAXONOMY_STORAGE_ERROR_H
#define SHARED_TAXONOMY_STORAGE_ERROR_H

typedef enum {
    ST_OK = 0,
    ST_ERROR_FILE_NOT_FOUND,
    ST_ERROR_PERMISSION,
    ST_ERROR_CORRUPT,
    ST_ERROR_FULL
} StorageError;

#endif /* SHARED_TAXONOMY_STORAGE_ERROR_H */
